### ISSUE TITLE
The enforcer always returns false after changing the policy definition.

### ISSUE THREAD

**Issue by zzl221000** [casbin/casbin-editor#14]
##### Overview of the issue
The enforcer always returns false after changing the policy definition.

##### the model conf

Example of configuration using RBAC

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, note,act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

##### Policy

```
p, alice, ok, data1, read
p, bob, oo, data2, write
p, data2_admin, what, data2, read
p, data2_admin, how ,data2, write

g, alice, data2_admin
```

##### my request
`bob, oo, write`

![image](https://user-images.githubusercontent.com/14102425/86897695-57970380-c13a-11ea-944a-00681a4f16e5.png)

**Comment by hsluoyz** [comment]
@zzl221000 no space after where: `some(where (p.eft == allow))`

**Comment by zzl221000** [comment]
@hsluoyz In the model syntax, the space after where is required. [casbin/Syntax for Models/Policy effect](https://casbin.org/docs/en/syntax-for-models#policy-effect)

**Comment by hsluoyz** [comment]
@zzl221000 need a space after comma:

```ini
[policy_definition]
p = sub, obj, note,act
```

**Comment by zzl221000** [comment]
@hsluoyz  Thanks, it's the spaces. The syntax looks a bit odd, it must be one space, not none or more!

**Comment by zzl221000** [comment]
@hsluoyz It looks like there's a problem with the model's configuration resolution.
Here are two inconsistent behaviors that occur when you add spaces in different places
one many space before note，enforcer is right
![image](https://user-images.githubusercontent.com/14102425/86938927-91d0c700-c173-11ea-9497-4a7b8a499dc0.png)

another many space before act ，enforcer is wrong
![image](https://user-images.githubusercontent.com/14102425/86939146-ca70a080-c173-11ea-8002-5a0763edcfea.png)

**Comment by nodece** [comment]
Thanks @zzl221000 for your report, I've summited a PR: https://github.com/casbin/node-casbin/pull/169 to fix it.

**Comment by hsluoyz** [comment]
@nodece merged, please release new version of Node-Casbin and update the dependency in this repo.

**Comment by hsluoyz** [comment]
@zzl221000 fixed in: https://github.com/casbin/casbin-editor/pull/15
