### ISSUE TITLE
domain with pattern (*) is not supported

### ISSUE THREAD

**Issue by DarkSorrow** [casbin/casbin-editor#16]
Hello,

I've been trying to use this file from the main casbin project rbac_with_domain_pattern_policy.csv in order to select a "*" for domain but it seems that this doesn't work using the provided conf and csv, is it because this is not yet available in the nodejs version?

**Comment by nodece** [comment]
currently, editor doesn't support the feature, but the feature is supported by node-casbin.

**Comment by hsluoyz** [comment]
@nodece I think the editor is also powered by Node-Casbin? So why Node-Casbin supports it while the editor doesn't?

**Comment by nodece** [comment]
Node-Casbin support the feature, but we need to add module to editor for support enable the feature.

**Comment by hsluoyz** [comment]
OK. @zhmushan can you do it?

**Comment by zhmushan** [comment]
Assigned to @zhmushan

**Comment by 00LT00** [comment]
@zhmushan @nodece Hello, can we add this function as soon as possible? In the one month, it has many user take issue for the domain with pattern(*). If the editor can support this feature, I think many user could solve the problem by themselves in Editor.

**Comment by hsluoyz** [comment]
@zhmushan 

/cc @nodece

**Comment by hsluoyz** [comment]
Any update?

**Comment by nodece** [comment]
@hsluoyz I'm going to add this feature tonight.
