### ISSUE TITLE
"Custom config" needs to be improved

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#163]
This "Custom config" is very hard to use. Take the custom function for example, we should allow the users to easily configure a custom function by following the docs: https://casbin.org/docs/function#how-to-add-a-customized-function, design a more friendly UI

![image](https://github.com/user-attachments/assets/b39ec584-e2dd-4e70-ac68-c9debf3888f3)

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive
