### ISSUE TITLE
The "RESET" button on editor does not works

### ISSUE THREAD

**Issue by dkjiaoyang** [casbin/casbin-editor#21]
Hi, I was editing on [casbin-editor](https://casbin.org/zh-CN/editor) and I found a problem. I thought it might be a bug.

#### Environment
Windows 10 Professional 20H2 19042.572
Firefox 82.0.2 (64bit)

#### Requirement & issue's  scene
I clicked the RESET button on editor

#### Expected result description 
I was wondering a RESET for all the text fields in this page, all the changes I just edit should be recovered to default.

#### Actual result description
After page refreshed, those text fields never recovered, and I found what I just edit in the localStorage of the browser.

#### Logs
None

#### Screenshot
![图片](https://user-images.githubusercontent.com/1768892/97965163-e79d3f00-1df4-11eb-9081-3f204e66f1ae.png)

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casbin/casbin-editor/pull/22
