### ISSUE TITLE
Make ABAC and all other features available for every option

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#31]
https://casbin.org/en/editor

Currently, if we don't choose ABAC in the drop-down, even if we specify a ABAC policy, it doesn't work.

See more details at: https://github.com/casbin/casbin-editor/issues/25#issuecomment-728799719

This confuses a lot of our users. We need to `make ABAC and all other features available for every option`.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by nodece** [comment]
I will work on this.
