### ISSUE TITLE
Wrong answer when requesting with || ?

### ISSUE THREAD

**Issue by skippy29** [casbin/casbin-editor#41]
Hi,

with model

```ini
# Request definition
[request_definition]
r = sub, action

# Policy definition
[policy_definition]
p = sub, action

# Policy effect
[policy_effect]
e = some(where (p.eft == allow))

# Matchers
[matchers]
m = (r.action == "dothejob" && r.sub == p.sub) || \
    (r.action == "undothejob" && r.sub == p.sub)
```

and policy

```
p, user1, dosomethingverynice

when requesting
user1, do thejob 
```

I get True

Is this expected behavior?

**Comment by hsluoyz** [comment]
@MRGUOKING @Gabriel-403

/cc @nodece @Zxilly

**Comment by MRGUOKING** [comment]
@skippy29 I think the result is true. This is ACL without Resources.  your r.action is "dothejob" and  r.sub (usr1)  == p.sub

**Comment by hsluoyz** [comment]
@skippy29 yes, you should simply use: `r.action == p.action && r.sub == p.sub`, similar to the basic ACL model.
