### ISSUE TITLE
"RBAC with pattern" doesn't pass initially

### ISSUE THREAD

**Issue by maxwell-carbon** [casbin/casbin-editor#42]
If I perform the following steps:
1. Go to https://casbin.org/en/editor
2. Choose `RBAC with pattern` from the dropdown.
3. Click `Reset` for good measure.
4. Click `RUN THE TEST`.

Then the Enforcement Result region says `false`, which is...unhelpful. I don't need failing examples, I need passing examples 😄 

The `RBAC with all pattern` fails similarly.

I've tried a bunch of random things to try to get it to pass, but so far I'm unsuccessful. Ideas I've had:
* Do we need to update the `Custom config` code ourselves? I've tried `keyMatch` and `keyMatch2` for both configuration values and neither worked.
* `regexMatch(r.act, p.act)` -- maybe this part is wrong? It seems like it should be a keyMatch and not a regex match (since there are no regexes in the policy), or it shouldn't be operating over the actions, but rather the subject.

**Comment by hsluoyz** [comment]
@nodece @Zxilly @Gabriel-403

**Comment by Zxilly** [comment]
working on this
