### ISSUE TITLE
Can create sharable links for people to share their model and policy with others

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#44]

**Comment by hsluoyz** [comment]
@turbodog03 plz work on it.

/cc @nodece

**Comment by turbodog03** [comment]
OK，working on it

**Comment by Zxilly** [comment]
Should we store it at the server, or just embed it in the URL?
Maybe we can store it at some pastebin?

**Comment by turbodog03** [comment]
> Should we store it at the server, or just embed it in the URL?
> Maybe we can store it at some pastebin?
I think use pastebin is a good idea, cause embed it in the URL will make it too long and hard to share.

**Comment by turbodog03** [comment]
> Should we store it at the server, or just embed it in the URL?
> Maybe we can store it at some pastebin?

I think use pastebin is a good idea, cause embed it in the URL will make it too long and hard to share.

**Comment by hsluoyz** [comment]
How to use it with pastebin ?

**Comment by Zxilly** [comment]
@hsluoyz we can create a plaintext structure to store the model, policies and the tests. Then use API to save this string to pastebin and get the link hash and save it in the url.

**Comment by nodece** [comment]
@Zxilly Sounds great.

**Comment by Zxilly** [comment]
@turbodog03 Any progress on this?

**Comment by turbodog03** [comment]
> @turbodog03 Any progress on this?

I met some difficulties and paused its progress, now I'm mainly woking on UI performance.  :(  Sorry for this...I should explain it earlier.

**Comment by hsluoyz** [comment]
Re-assigned to @Zxilly @Gabriel-403

**Comment by Zxilly** [comment]
> @hsluoyz we can create a plaintext structure to store the model, policies and the tests. Then use API to save this string to pastebin and get the link hash and save it in the url.

@hsluoyz Maybe we should setup a reverse-proxy for pastebin. Browser will block those cross-domain request without CSRF headers.
