### ISSUE TITLE
Automate the deployment with Travis CI

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#5]
See: https://github.com/casbin/casbin-editor/pull/4

**Comment by nodece** [comment]
What do you think the Github Actions？

**Comment by hsluoyz** [comment]
Sure. You can try it. I also want to learn GitHub Actions.

**Comment by nodece** [comment]
@hsluoyz You need add `GITHUB_TOKEN` to `GitHub Actions`.

**Comment by nodece** [comment]
I submitted a PR: #6 

when merged, you need add `GITHUB_TOKEN` to `GitHub Actions`.

**Comment by hsluoyz** [comment]
How to add?

**Comment by nodece** [comment]
See: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets.

**Comment by hsluoyz** [comment]
I added you to Admins of this repo. You can configure it by yourself now.

![image](https://user-images.githubusercontent.com/3787410/78626462-6e228a00-78c1-11ea-9397-c237464db9a3.png)

**Comment by hsluoyz** [comment]
Then you can merge: https://github.com/casbin/casbin-editor/pull/7 to see whether it works.

**Comment by nodece** [comment]
Thanks @hsluoyz, It works fine!
