### ISSUE TITLE
Add netlify preview for PRs like this

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#53]
Add netlify preview for PRs like this: https://github.com/casbin/casbin-website/pull/258#issuecomment-884322945

**Comment by hsluoyz** [comment]
@ErikQQY @Zxilly

**Comment by ErikQQY** [comment]
Working on this

**Comment by Zxilly** [comment]
@hsluoyz Maybe this should configured on https://app.netlify.com/
