### ISSUE TITLE
Error: Unclosed ( at character 72

### ISSUE THREAD

**Issue by lantu-group** [casbin/casbin-editor#60]
I test by [rbac_model_matcher_using_in_op.conf](https://github.com/casbin/casbin/blob/277c1a2b85698272f764d71a94d2595a8d425915/examples/rbac_model_matcher_using_in_op.conf),  and got a grammar error: Unclosed ( at character 72

Env: node-casbin: "^5.11.1",

**Comment by hsluoyz** [comment]
@nodece @Zxilly @Gabriel-403

**Comment by Gabriel-403** [comment]
> @nodece @Zxilly @Gabriel-403

working on this

**Comment by Zxilly** [comment]
@lantu-group You use the wrong syntax.
Here is a corrected version. https://casbin.org/casbin-editor/#9ZMVJFNZX

**Comment by hsluoyz** [comment]
@Zxilly the docs said `in` should use "(xxx)" instead of "[xxx]": https://casbin.org/docs/en/syntax-for-models#special-grammer

We should unify the grammar and update the docs.

**Comment by nodece** [comment]
@Gabriel-403 @Zxilly could you update `casbin` to latest version for fix this issue?
