### ISSUE TITLE
Allow to specify the attributes (struct) for the ABAC model

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-editor#8]
@nodece , currently, there's no way to let users provide the attributes in ABAC in our editor: https://casbin.org/en/editor. We need to add this.

This issue is originally raised in: https://casbin.org/en/editor#comment-4485545919

**Comment by hsluoyz** [comment]
@nodece @GopherJ @DivyPatel9881 can anyone work on it?

**Comment by DivyPatel9881** [comment]
Okay, I can work on this issue.

**Comment by nodece** [comment]
@DivyPatel9881 I added the feature to casbin-editor.

**Comment by mouslimdiallo** [comment]
Le problème de spécification des attributs avec ABAC est-il résolu ?

**Comment by hsluoyz** [comment]
> Le problème de spécification des attributs avec ABAC est-il résolu ?

@mouslimdiallo hi, plz use English.

**Comment by mouslimdiallo** [comment]
Is the problem of specifying attributes with ABAC resolved? I am working on a web services application. I want to implement it with java?

**Comment by hsluoyz** [comment]
@mouslimdiallo already done long ago: https://github.com/casbin/casbin-editor/commit/f50dd523852434da75740a2f38341b97c4bbe866

see:

![image](https://user-images.githubusercontent.com/3787410/128534457-d326b52f-a462-4e5c-83d6-002477194be2.png)
