### ISSUE TITLE
[Question] can we use ipMatch in a police rule?

### ISSUE THREAD

**Issue by skyfall2022** [casbin/casbin-editor#86]
**Want to prioritize this issue? Try:**

[![issuehunt-to-marktext](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg)](https://issuehunt.io/r/casbin/casbin)

[------](https://editor.casbin.org/#2SDNJPHGE)

**What's your scenario? What do you want to achieve?**
deny the request of some type of devices from some ip addresses

**Your model:**

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_rule, obj, act, eft

[policy_effect]
e = !some(where (p.eft == deny))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
```

**Your policy:**

```
p, r.sub.Device == 'Android', file, send, deny
p, r.sub.Device == 'Windows' && ipMatch(r.sub.Ip, '10.0.0.0/24'), file, save, deny
```

**Your request(s):**

```
{Device:'Android',Ip:'10.1.0.3'}, file, send
{Device:'iOS',Ip:'10.0.0.2'}, file, save
```

**Comment by nodece** [comment]
Please update your policy:
```
p, r.sub.Device == 'Android', file, send, deny
p, "r.sub.Device == 'IOS' && ipMatch(r.sub.Ip,'10.0.0.0/24')", file, save, deny
```
